name: Build

on:
  push:
    branches:
      - "*"
      - "*/*"
  workflow_dispatch:


jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            paulomartde/fast_texlive
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=sha

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |-
              linux/amd64
              linux/arm64
          file: ./Dockerfile
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
